### PR TITLE
When destroying a cookie the path is not set

### PR DESCRIPTION
**Pull request by johannes85**

### CODE REVIEW

**Comment by thekid** [comment]
Wouldn't this also be valid for other attributes like domain, sameSite etcetera?

**Comment by johannes85** [comment]
I think only domain would matter

**Comment by thekid** [comment]
> I think only domain would matter

Can you verify this with the official RFC, MDN or other sources?

**Comment by johannes85** [comment]
Nope

**Comment by thekid** [comment]
According to your report, the following code should fail to work:

```php
<?php

use util\Objects;
use web\{Application, Cookie};

class Cookies extends Application {

  public function routes() {
    return [
      '/admin/login' => function($req, $res) {
        $res->cookie((new Cookie('session', 'value'))->path('/admin'));
        $res->answer(302);
        $res->header('Location', '/admin');
      },
      '/admin/logout' => function($req, $res) {
        $res->cookie(new Cookie('session', null));
        $res->answer(302);
        $res->header('Location', '/admin');
      },
      '/admin' => function($req, $res) {
        $value= $req->cookies();
        $res->send('<html>
          <head><title>Admin area</title></head>
          <body>
            <p>Admin area cookies are '.Objects::stringOf($value).'</p>
            <a href="/admin/login">Login</a> | <a href="/admin/logout">Logout</a>  | <a href="/">Public area</a>
          </body>
        </html>');
      },
      '/' => function($req, $res) {
        $value= $req->cookies();
        $res->send('<html>
          <head><title>Public area</title></head>
          <body>
            <p>Public area cookies are '.Objects::stringOf($value).'</p>
            <a href="/admin">Admin area</a>
          </body>
        </html>');
      },
    ];
  }
}
```

...and require line 16 to read `$res->cookie((new Cookie('session', null))->path('/admin'));`. In Chrome, Chrome-based Edge and Firefox Nightly and using curl, it works fine (🙄), which it shouldn't according to your report. The only browsers I can reproduce your observation with are Edge and Internet Explorer.

However, some research reveals path and domain (and only these!) are relevant when deleting cookies:

* https://api.rubyonrails.org/v5.1.7/classes/ActionDispatch/Cookies.html 
* https://github.com/js-cookie/js-cookie (see README)
* https://github.com/7leads/ngx-cookie-service/blob/1886b06af5b9cfcd20376918337ef937efa23bea/lib/cookie-service/cookie.service.ts#L139

I would've wished that you provide these insights instead of requesting to change the library based solely on personal belief what is right.

**Comment by thekid** [comment]
See xp-forge/web@9d6641a and https://travis-ci.org/xp-forge/sessions/builds/584765156

**Comment by thekid** [comment]
:shipit: https://github.com/xp-forge/sessions/releases/tag/v1.0.1

**Comment by johannes85** [comment]
@thekid 
Your code isn't producing the error haoppened withthe session class so i changed it to reproduce is:

```PHP
<?php

use util\Objects;
use web\{Application, Cookie};

class Cookies extends Application {

  public function routes() {
    return [
      '/login' => function($req, $res) {
        $res->cookie((new Cookie('session', 'value'))->path('/admin'));
        $res->answer(302);
        $res->header('Location', '/admin');
      },
      '/logout' => function($req, $res) {
        $res->cookie(new Cookie('session', null));
        $res->answer(302);
        $res->header('Location', '/admin');
      },
      '/admin' => function($req, $res) {
        $value= $req->cookies();
        $res->send('<html>
          <head><title>Admin area</title></head>
          <body>
            <p>Admin area cookies are '.Objects::stringOf($value).'</p>
            <a href="/login">Login</a> | <a href="/admin/logout">Logout</a>  | <a href="/">Public area</a>
          </body>
        </html>');
      },
      '/' => function($req, $res) {
        $value= $req->cookies();
        $res->send('<html>
          <head><title>Public area</title></head>
          <body>
            <p>Public area cookies are '.Objects::stringOf($value).'</p>
            <a href="/admin">Admin area</a>
          </body>
        </html>');
      },
    ];
  }
}
```

Now when loggin in the cookie gets set for the /admin dir but can't be deleted since the dir is missing when removing the cookie.

**Comment by thekid** [comment]
> so i changed it to reproduce is:

These kinds of reproduce scripts would be much welcome right from the beginning.

**Pull request closed without merging**
